#!/bin/bash

export CondaDIR=/mnt/wk2/recommend_model/performance/Environment/anaconda3
export PATH=$CondaDIR/bin:$PATH

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('$CondaDIR/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$CondaDIR/etc/profile.d/conda.sh" ]; then
        . "$CondaDIR/etc/profile.d/conda.sh"
    else
        export PATH="$CondaDIR/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

### PERFORMANCE OPTIONS SET ###
set optrun = $1  # Met, Evalute, Taiwan  : MetEva_Taiwan_d04.py
source activate Evaluate
#cd ../Met_Evaluate_tool/Taiwan_d04
#python MetEva_Taiwan_d04.py
cd ../Air_plot_tool/
python Air_plot2D.py
